config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# Controls questions
class QuestionsController < ApplicationController
  def ask() end

  def answer
    @question = params['question']

    @answer = if @question == 'I am going to work'
                'Great!'
              elsif @question[-1] == '?'
                'Silly question, get dressed and go to work!'
              else
                "I don't care, get dressed and go to work!"
              end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <h1>Stupid Coaching</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="quote">
  <p><%= @question %></p>
  <p class="user">-You</p>
</div>

<div class="quote" id="coach">
  <p><%= @answer %></p>
  <p class="user">-Your coach</p>
</div>


<%= link_to 'Ask a new question', ask_path %>

app/views/questions/ask.html.erb
<form action="/answer" data-turbo="false" id="questionForm">
  <input type="text" name="question" placeholder="Ask your coach anything...">
  <input type="submit" value="Ask">
</form>